name: Maven Action
description: Maven Action
inputs:
  path_dockerfile:
    description: "Dockerfile Path Description"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Image Description"
    required: true
  tag_name:
    description: "Tag Description"
    required: true
runs:
  using: composite
  steps:
    - name: Maven Run Build
      run:
        if [ -z "${{ inputs.tag_name }}" ]; then
          export TAG=$(date +%s)
        else
          export TAG="${{ inputs.tag_name }}"
        fi
          docker build . --file {{path_dockerfile}} --tag {{image_name}}:{{tag_name}}
      shell: bash